### ISSUE TITLE
 error LNK2001 at install windows 

### ISSUE THREAD

**Issue by ecus** [nukedzn/node-informix#55]
$ npm install --save informix

> informix@0.7.0 install C:\wamp64\www\ecus\node_modules\informix
> node-gyp rebuild

C:\wamp64\www\ecus\node_modules\informix>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\wamp64\www\ecus\node_modules\informix\build\..\build\esqlc.c
Los proyectos de esta soluci▒n se van a compilar de uno en uno. Para habilitar la compilaci▒n en paralelo, agregue el modificador "/m".
  prepare
          1 archivo(s) copiado(s).
  esql-preprocess
  esqlc: "release\obj\esqlc\src\esqlc.ec", line 19: Warning -33011: Current declaration of 'esql_user' hides previous declaration.
  esqlc: "release\obj\esqlc\src\esqlc.ec", line 20: Warning -33011: Current declaration of 'esql_pass' hides previous declaration.
  2 warning(s)
  IBM Informix CSDK Version 3.50, IBM Informix-ESQL Version 3.50.TC6
  move
  Se han movido         1 archivos.
  module.cpp
  ifx.cpp
  connect.cpp
  disconnect.cpp
c:\program files (x86)\ibm\informix\client-sdk\incl\esql\datetime.h(37): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) (compiling source file ..\src\ifx\ifx.cpp) [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
  stmtprepare.cpp
  stmtexec.cpp
  stmtfree.cpp
  fetch.cpp
  cursorclose.cpp
  esqlc.cpp
  win_delay_load_hook.cc
c:\program files (x86)\ibm\informix\client-sdk\incl\esql\datetime.h(37): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) (compiling source file C:\wamp64\www\ecus\node_modules\informix\build\Release\obj\global_intermediate\src\esqlc.cpp) [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
     Creating library C:\wamp64\www\ecus\node_modules\informix\build\Release\ifx.lib and object C:\wamp64\www\ecus\node_modules\informix\build\Release\ifx.exp
ifx.obj : error LNK2001: unresolved external symbol rtypalign [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
ifx.obj : error LNK2001: unresolved external symbol rtypmsize [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
disconnect.obj : error LNK2001: unresolved external symbol SqlFreeMem [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol rfmtdate [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol ifx_int8toasc [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol intofmtasc [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol dectoasc [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol dttofmtasc [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol dectodbl [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
fetch.obj : error LNK2001: unresolved external symbol ifx_int8tolong [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol fnsqlcode [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_curs_decl_dynm [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_curs_open [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_connect_close [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol fnsqlstate [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_curs_close [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_connect_set [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_curs_fetch [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol ifx_free_conn_user [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_mt_free [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_exec [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_connect_open [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_describe_input_stmt [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_prep [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_curs_locate [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol sqli_describe_output_stmt [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol rgetlmsg [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol ifx_alloc_conn_user [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
esqlc.obj : error LNK2001: unresolved external symbol fnsqlca [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
C:\wamp64\www\ecus\node_modules\informix\build\Release\ifx.node : fatal error LNK1120: 29 unresolved externals [C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\wamp64\www\ecus\node_modules\informix
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\wamp64\www\ecus\package.json'
npm WARN ecus No description
npm WARN ecus No repository field.
npm WARN ecus No README data
npm WARN ecus No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! informix@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the informix@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Programador1\AppData\Roaming\npm-cache\_logs\2018-03-17T13_51_51_933Z-debug.log

**My enviroment variables:**

**INFORMIXDIR**=C:\Program Files (x86)\IBM\Informix\Client-SDK
**LD_LIBRARY_PATH**=C:\Program Files (x86)\IBM\Informix\Client-SDK\lib;C:\Program Files (x86)\IBM\Informix\Client-SDK\lib\esql;C:\Program Files (x86)\IBM\Informix\Client-SDK\incl\esql

I'm tyring to install in a client

**Comment by uditha-atukorala** [comment]
Looking at the logs and error it seems like it is failing to find the CSDK ESQL libs to link to :thinking:.

**Comment by ecus** [comment]
antything I could do?

**Comment by uditha-atukorala** [comment]
Can you check the following files exist ([binding.gyp:94](https://github.com/nukedzn/node-informix/blob/b00ab50d26eb78530051a816fcc8007d70210a37/binding.gyp#L94))?

- $(INFORMIXDIR)/lib/isqlt09a.lib
- $(INFORMIXDIR)/lib/igl4n304.lib
- $(INFORMIXDIR)/lib/iglxn304.lib
- $(INFORMIXDIR)/lib/igo4n304.lib

**Comment by ecus** [comment]
```
16/03/2018  05:34 p.m.    <DIR>          .
16/03/2018  05:34 p.m.    <DIR>          ..
11/12/2017  09:39 a.m.    <DIR>          client
11/12/2017  09:39 a.m.    <DIR>          cpp
11/12/2017  09:39 a.m.    <DIR>          dmi
15/12/2009  07:06 a.m.           479,232 eprotect.exe
15/12/2009  07:06 a.m.         1,376,256 esqlc.exe
15/12/2009  07:06 a.m.         1,314,816 esqlcdb2.exe
15/12/2009  07:06 a.m.           466,944 esqlmf.exe
15/12/2009  07:06 a.m.            22,888 iclit09b.lib
15/12/2009  07:06 a.m.           203,318 idb2t09a.lib
15/12/2009  07:06 a.m.            69,534 **igl4n304.lib**
15/12/2009  07:06 a.m.             1,726 **iglxn304.lib**
15/12/2009  07:06 a.m.             5,452 **igo4n304.lib**
15/12/2009  07:06 a.m.             5,954 iregt07b.lib
15/12/2009  07:06 a.m.           214,728 **isqlt09a.lib**
15/12/2009  07:06 a.m.         7,213,344 isqlt09s.lib
```

**Comment by uditha-atukorala** [comment]
Not really sure why it isn't working if the files are there and the environment variables are set correctly. You could try opening the VC project (`C:\wamp64\www\ecus\node_modules\informix\build\ifx.vcxproj`) in Visual Studio and try to compile there and see if you get more meaningful errors.

**Comment by uditha-atukorala** [comment]
@ecus, did you manage to solve your build problems?

**Comment by ecus** [comment]
Yes, i was working with CSDK 3.50,  so i had to reinstall version CSDK 3.70, and it built without troubles.
